import type { Account, CalendarItem, Competitor, ContentItem, Goal, Platform } from '../types'

export const platformColors: Record<Platform, string> = {
  Bilibili: '#2563eb',
  Xiaohongshu: '#e11d48',
  Douyin: '#111827',
}

export const platformSoftColors: Record<Platform, string> = {
  Bilibili: '#dbeafe',
  Xiaohongshu: '#ffe4e6',
  Douyin: '#e5e7eb',
}

export const seedContent: ContentItem[] = [
  {
    id: 'seed-001',
    platform: 'Bilibili',
    title: '独立开发者如何用 AI 在 3 个月内做出可售产品',
    type: '长视频',
    publishedAt: '2026-05-28',
    hour: 10,
    views: 45200,
    likes: 3200,
    comments: 620,
    shares: 480,
    saves: 910,
    followersGained: 410,
    pillar: '独立开发',
    campaign: 'AI 工具线',
  },
  {
    id: 'seed-002',
    platform: 'Xiaohongshu',
    title: '我的第一套独立开发工具箱分享',
    type: '图文笔记',
    publishedAt: '2026-05-25',
    hour: 21,
    views: 28400,
    likes: 5100,
    comments: 740,
    shares: 820,
    saves: 2300,
    followersGained: 520,
    pillar: '工具清单',
    campaign: 'AI 工具线',
  },
  {
    id: 'seed-003',
    platform: 'Douyin',
    title: '3 个小技巧让你的内容更容易被转发',
    type: '短视频',
    publishedAt: '2026-05-22',
    hour: 12,
    views: 89200,
    likes: 12400,
    comments: 1300,
    shares: 1820,
    saves: 1460,
    followersGained: 870,
    pillar: '内容增长',
    campaign: '增长实验',
  },
  {
    id: 'seed-004',
    platform: 'Bilibili',
    title: '从 0 到 MVP：一次完整产品构建复盘',
    type: '长视频',
    publishedAt: '2026-05-20',
    hour: 9,
    views: 31800,
    likes: 2100,
    comments: 410,
    shares: 330,
    saves: 760,
    followersGained: 260,
    pillar: '产品复盘',
    campaign: 'MVP 复盘',
  },
  {
    id: 'seed-005',
    platform: 'Xiaohongshu',
    title: '个人创作者的 2026 增长复盘模板',
    type: '图文笔记',
    publishedAt: '2026-05-18',
    hour: 20,
    views: 15600,
    likes: 2890,
    comments: 360,
    shares: 410,
    saves: 1800,
    followersGained: 310,
    pillar: '复盘模板',
    campaign: '增长实验',
  },
  {
    id: 'seed-006',
    platform: 'Douyin',
    title: '如何用手机拍出电影感产品短片',
    type: '短视频',
    publishedAt: '2026-05-15',
    hour: 19,
    views: 67500,
    likes: 9800,
    comments: 870,
    shares: 1160,
    saves: 980,
    followersGained: 650,
    pillar: '拍摄方法',
    campaign: '增长实验',
  },
  {
    id: 'seed-007',
    platform: 'Bilibili',
    title: '开源工具推荐：提升生产力的 5 款神器',
    type: '长视频',
    publishedAt: '2026-05-12',
    hour: 11,
    views: 22100,
    likes: 1450,
    comments: 280,
    shares: 210,
    saves: 560,
    followersGained: 180,
    pillar: '工具清单',
    campaign: 'AI 工具线',
  },
  {
    id: 'seed-008',
    platform: 'Xiaohongshu',
    title: '我的桌面工作流分享 2026 版',
    type: '图文笔记',
    publishedAt: '2026-05-10',
    hour: 22,
    views: 19800,
    likes: 3720,
    comments: 420,
    shares: 520,
    saves: 1650,
    followersGained: 330,
    pillar: '工作流',
    campaign: 'AI 工具线',
  },
]

export const seedAccounts: Account[] = [
  { platform: 'Bilibili', handle: '@overlook_creator', status: 'manual', followers: 12400, lastSync: '2026-06-01' },
  { platform: 'Xiaohongshu', handle: '@overlook_creator', status: 'manual', followers: 8700, lastSync: '2026-06-01' },
  { platform: 'Douyin', handle: '@overlook_creator', status: 'manual', followers: 18900, lastSync: '2026-06-01' },
]

export const seedCompetitors: Competitor[] = [
  {
    id: 'comp-001',
    platform: 'Xiaohongshu',
    name: '同赛道工具博主 A',
    followers: 53000,
    avgViews: 36000,
    engagementRate: 18.4,
    angle: '模板下载 + 个人经历',
  },
  {
    id: 'comp-002',
    platform: 'Bilibili',
    name: '独立开发频道 B',
    followers: 92000,
    avgViews: 52000,
    engagementRate: 9.6,
    angle: '项目拆解 + 代码演示',
  },
  {
    id: 'comp-003',
    platform: 'Douyin',
    name: '效率工具短视频 C',
    followers: 118000,
    avgViews: 76000,
    engagementRate: 13.1,
    angle: '强钩子 + 三段式口播',
  },
]

export const seedGoal: Goal = {
  month: '2026-06',
  targetViews: 360000,
  targetFollowers: 3200,
  targetSponsorLeads: 8,
}

export const seedCalendar: CalendarItem[] = [
  {
    id: 'cal-001',
    day: '周一',
    platform: 'Bilibili',
    title: '把爆款短视频扩展成长视频复盘',
    format: '长视频',
    time: '10:00',
    objective: '沉淀信任',
    status: 'scheduled',
  },
  {
    id: 'cal-002',
    day: '周三',
    platform: 'Xiaohongshu',
    title: '工具箱清单拆成 6 张图文卡片',
    format: '图文笔记',
    time: '21:00',
    objective: '收藏增长',
    status: 'draft',
  },
  {
    id: 'cal-003',
    day: '周五',
    platform: 'Douyin',
    title: '用 15 秒钩子复述本周最高保存内容',
    format: '短视频',
    time: '12:00',
    objective: '拉新',
    status: 'draft',
  },
]
